[build]
  publish = "public"
  command = "npm run build && php artisan config:cache && php artisan route:cache && php artisan view:cache"

[build.environment]
  PHP_VERSION = "8.2"
  NODE_VERSION = "18"

[[redirects]]
  from = "/api/*"
  to = "/index.php"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.php"
  status = 200

[functions]
  directory = "functions"

[dev]
  publish = "public"
  command = "php artisan serve --host=0.0.0.0 --port=8888"
  port = 8888
